Various fixes
hyprwm/Hypr pull request #103
Opened 2023-01-23 15:14 UTC by end-4

# Fixes
- Workspace animation fix: left-to-right and right-to-left instead of just left-to-right (and enable it by default)
- Fixed resize speed of y dimension (for tiled windows) 
# Added features
- Adjustable `splitratio` dispatcher's speed (for example `+0.1` instead of `+`)
- Added a separate value for resize animation speed (for tiled windows)

(also sorry for that messy commit history...)

2023-01-23 18:09 UTC, vaxerski requested changes
and in general if you could also make a tight list of changes needed to the wiki as iirc I have to edit it manually (cuz gh wiki)

2023-01-23 18:09 UTC, vaxerski commented on src/config/ConfigManager.cpp
> +    configValues["animations:windowresizespeed"].floatValue = 1;
can this be in snake_case to keep unity with the rest of the config plox

2023-01-23 18:09 UTC, vaxerski commented on src/windowManager.cpp
> +    else {
{} not needed

2023-01-23 18:09 UTC, vaxerski commented on src/windowManager.cpp
> +    else {  // Wipe from right to left (oldwork < newwork)
} else {

2023-01-24 00:05 UTC, end-4 commented on src/config/ConfigManager.cpp
> +    configValues["animations:windowresizespeed"].floatValue = 1;
https://github.com/end-4/hyprland-is-great-but-i-want-xorg/commit/0bcb72e3c3476c23d08f0f127e50a1b594f035bb

2023-01-24 00:05 UTC, end-4 commented on src/windowManager.cpp
> +    else {
https://github.com/end-4/hyprland-is-great-but-i-want-xorg/commit/0bcb72e3c3476c23d08f0f127e50a1b594f035bb

2023-01-24 00:05 UTC, end-4 commented on src/windowManager.cpp
> +    else {  // Wipe from right to left (oldwork < newwork)
https://github.com/end-4/hyprland-is-great-but-i-want-xorg/commit/0bcb72e3c3476c23d08f0f127e50a1b594f035bb

2023-01-24 19:00 UTC, vaxerski requested changes
all good except for this mistake

2023-01-24 19:00 UTC, vaxerski commented on src/utilities/AnimationUtil.cpp
> +    const double RESIZEANIMATIONSPEED = std::max(1.f / ((double)ConfigManager::getFloat("animations:windowresizespeed") * DELTA) * 462.f, (double)1.f);
forgot to use here the new name

2023-01-25 00:10 UTC, end-4 commented on src/utilities/AnimationUtil.cpp
> +    const double RESIZEANIMATIONSPEED = std::max(1.f / ((double)ConfigManager::getFloat("animations:windowresizespeed") * DELTA) * 462.f, (double)1.f);
https://github.com/hyprwm/Hypr/commit/c71f05473ee0c04e64496df019dd6542a60c474a

2023-01-25 12:56 UTC, vaxerski approved these changes

2023-01-25 12:56 UTC, vaxerski commented
thanks!

2023-01-25 13:00 UTC, merged